# Generated by Django 5.2.14 on 2026-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=225)),
                ('duration', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
