# Generated by Django 5.2.14 on 2026-06-04 17:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_appoiment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoiment',
            new_name='Appointment',
        ),
    ]
