# Generated by Django 5.2.14 on 2026-06-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['services']},
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='services',
            table='services',
        ),
    ]
